import PDFDocument from 'pdfkit';

import { IComplianceScan } from '../models/ComplianceScan';

const DISCLAIMER =
  'This report is generated by AI for informational purposes only and does not constitute legal advice. Consult a qualified attorney for compliance decisions.';

function getScoreColor(score: number): string {
  if (score < 50) return '#DC2626';
  if (score < 70) return '#D97706';
  return '#16A34A';
}

function getSeverityColor(severity: string): string {
  switch (severity) {
    case 'critical':
      return '#991B1B';
    case 'high':
      return '#B45309';
    case 'medium':
      return '#1D4ED8';
    default:
      return '#15803D';
  }
}

function drawFooter(doc: PDFKit.PDFDocument): void {
  const bottomY = doc.page.height - 42;
  doc
    .fontSize(8)
    .fillColor('#6B7280')
    .text(DISCLAIMER, 42, bottomY, {
      width: doc.page.width - 84,
      align: 'center',
      lineBreak: false,
    });
}

function scoreBar(doc: PDFKit.PDFDocument, label: string, score: number, y: number): void {
  const x = 70;
  const width = 420;
  const height = 16;
  const fillWidth = Math.max(0, Math.min(width, (score / 100) * width));
  const color = getScoreColor(score);

  doc.fontSize(12).fillColor('#111827').text(label, x, y);
  doc.fontSize(11).fillColor('#374151').text(`${score}/100`, x + width - 50, y);

  const barY = y + 20;
  doc.roundedRect(x, barY, width, height, 4).fillAndStroke('#E5E7EB', '#D1D5DB');
  doc.roundedRect(x, barY, fillWidth, height, 4).fill(color);
}

function statusCell(status: string): { text: string; color: string } {
  if (status === 'pass') return { text: '✓ pass', color: '#16A34A' };
  if (status === 'fail') return { text: '✗ fail', color: '#DC2626' };
  if (status === 'warning') return { text: '⚠ warning', color: '#D97706' };
  return { text: 'na', color: '#6B7280' };
}

function inferRegulation(item: string): string {
  const lower = item.toLowerCase();
  if (lower.includes('california') || lower.includes('do not sell') || lower.includes('non-discrimination')) {
    return 'CCPA §1798.100';
  }
  if (lower.includes('cookie')) {
    return 'PECR Reg. 6';
  }
  if (lower.includes('security') || lower.includes('encryption') || lower.includes('breach')) {
    return 'GDPR Art. 32';
  }
  if (lower.includes('retention') || lower.includes('delete')) {
    return 'GDPR Art. 5(1)(e)';
  }
  return 'GDPR Art. 13';
}

export async function generateComplianceReport(scan: IComplianceScan): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks: Buffer[] = [];

  const result = new Promise<Buffer>((resolve, reject) => {
    doc.on('data', (chunk) => chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  const now = new Date();
  const reportDate = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const scoreColor = getScoreColor(scan.scores.overall);

  // PAGE 1 — Cover
  doc.fontSize(30).fillColor('#111827').text('Compliance Snapshot Report', 50, 90);
  doc.fontSize(14).fillColor('#4B5563').text(`Domain: ${scan.domain}`, 50, 150);
  doc.text(`Scanned URL: ${scan.url}`, 50, 172);
  doc.text(`Generated on: ${reportDate}`, 50, 194);

  doc
    .fontSize(56)
    .fillColor(scoreColor)
    .text(`${scan.scores.overall}`, 50, 250, { width: 200, align: 'left' });
  doc.fontSize(18).fillColor('#374151').text('/100 overall score', 170, 280);

  const badgeColor = getSeverityColor(scan.riskLevel);
  doc.roundedRect(50, 340, 160, 34, 8).fill(badgeColor);
  doc
    .fontSize(14)
    .fillColor('#FFFFFF')
    .text(`Risk: ${scan.riskLevel.toUpperCase()}`, 62, 351, { width: 140, align: 'center' });

  doc.fontSize(12).fillColor('#6B7280').text('Generated by Aether AI Compliance Tool', 50, 420);
  drawFooter(doc);

  // PAGE 2 — Score Breakdown
  doc.addPage();
  doc.fontSize(24).fillColor('#111827').text('Score Breakdown', 50, 60);

  scoreBar(doc, 'GDPR', scan.scores.gdpr, 120);
  scoreBar(doc, 'CCPA', scan.scores.ccpa, 180);
  scoreBar(doc, 'Cookies', scan.scores.cookieCompliance, 240);
  scoreBar(doc, 'Retention', scan.scores.dataRetention, 300);
  const securityScore = Math.round(((scan.scores.userRights || 0) + (scan.scores.dataSharing || 0)) / 2);
  scoreBar(doc, 'Security', securityScore, 360);
  drawFooter(doc);

  // PAGE 3+ — Risk Flags
  const sortedFlags = [...scan.riskFlags].sort((a, b) => {
    const rank: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
    return (rank[a.severity] ?? 99) - (rank[b.severity] ?? 99);
  });

  let flagIndex = 0;
  while (flagIndex < Math.max(1, sortedFlags.length)) {
    doc.addPage();
    doc.fontSize(24).fillColor('#111827').text('Risk Flags', 50, 60);

    let y = 100;
    const pageFlags = sortedFlags.slice(flagIndex, flagIndex + 10);

    if (pageFlags.length === 0) {
      doc.fontSize(12).fillColor('#374151').text('No risk flags identified.', 50, y);
    }

    for (const flag of pageFlags) {
      const sevColor = getSeverityColor(flag.severity);
      doc.roundedRect(50, y + 2, 80, 18, 4).fill(sevColor);
      doc.fontSize(9).fillColor('#FFFFFF').text(flag.severity.toUpperCase(), 56, y + 8, { width: 68, align: 'center' });

      doc.fontSize(12).fillColor('#111827').text(flag.title, 140, y, { width: 400 });
      y += 20;
      doc.fontSize(10).fillColor('#374151').text(`Description: ${flag.description}`, 50, y, { width: 500 });
      y += 24;
      doc.text(`Recommendation: ${flag.recommendation}`, 50, y, { width: 500 });
      y += 24;
      doc.fillColor('#1F2937').text(`Regulation: ${flag.regulation}`, 50, y, { width: 500 });
      y += 28;
    }

    drawFooter(doc);
    flagIndex += 10;
  }

  // PAGE 4 — Checklist
  doc.addPage();
  doc.fontSize(24).fillColor('#111827').text('Checklist', 50, 60);

  const colX = [50, 250, 330, 470];
  doc.fontSize(10).fillColor('#111827').text('Item', colX[0], 100);
  doc.text('Status', colX[1], 100);
  doc.text('Details', colX[2], 100);
  doc.text('Regulation', colX[3], 100);

  let rowY = 120;
  for (const item of scan.checklist) {
    if (rowY > 730) {
      drawFooter(doc);
      doc.addPage();
      rowY = 70;
    }

    const st = statusCell(item.status);
    doc.fontSize(9).fillColor('#111827').text(item.item, colX[0], rowY, { width: 190 });
    doc.fillColor(st.color).text(st.text, colX[1], rowY, { width: 70 });
    doc.fillColor('#374151').text(item.details, colX[2], rowY, { width: 130 });
    doc.fillColor('#1F2937').text(inferRegulation(item.item), colX[3], rowY, { width: 90 });
    rowY += 40;
  }
  drawFooter(doc);

  // PAGE 5 — AI Summary + Recommendations
  doc.addPage();
  doc.fontSize(24).fillColor('#111827').text('AI Summary & Recommendations', 50, 60);

  doc.fontSize(13).fillColor('#111827').text('Executive Summary', 50, 110);
  doc.fontSize(11).fillColor('#374151').text(scan.aiAnalysis || 'No AI analysis available.', 50, 132, { width: 500 });

  const quickWins = scan.riskFlags.slice(0, 3).map((flag) => flag.recommendation).filter(Boolean);
  doc.fontSize(13).fillColor('#111827').text('Quick Wins', 50, 300);

  if (quickWins.length === 0) {
    doc.fontSize(11).fillColor('#374151').text('No quick wins available.', 50, 324);
  } else {
    quickWins.forEach((win, index) => {
      doc.fontSize(11).fillColor('#374151').text(`${index + 1}. ${win}`, 50, 324 + index * 24, { width: 500 });
    });
  }

  doc
    .fontSize(9)
    .fillColor('#6B7280')
    .text('Legal disclaimer: This AI-generated summary is informational and should be reviewed by legal counsel.', 50, 730, {
      width: 500,
      align: 'left',
    });

  drawFooter(doc);

  doc.end();
  return result;
}
